add julia support to dockerfile

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,8 +1,17 @@
 # pull official base image
-FROM node:latest
+FROM node:alpine
 
 # set working directory
 WORKDIR /server
+
+# Install alpine dependencies
+RUN apk add --no-cache python python-dev python3 python3-dev \
+    linux-headers build-base bash git ca-certificates && \
+    python3 -m ensurepip && \
+    rm -r /usr/lib/python*/ensurepip && \
+    pip3 install --upgrade pip setuptools && \
+    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
+    rm -r /root/.cache
 
 # add `/server/node_modules/.bin` to $PATH
 ENV PATH /server/node_modules/.bin:$PATH
@@ -12,10 +21,62 @@ COPY package.json ./
 COPY package-lock.json ./
 RUN npm install
 
-RUN npm rebuild node-pty --rebuild-binary
+# Julia 
+ENV JULIA_PATH /usr/local/julia
+ENV PATH $JULIA_PATH/bin:$PATH
+
+# https://julialang.org/juliareleases.asc
+# Julia (Binary signing key) <buildbot@julialang.org>
+ENV JULIA_GPG 3673DF529D9049477F76B37566E3C7DC03D6E495
+
+# https://julialang.org/downloads/
+ENV JULIA_VERSION 1.5.3
+
+RUN set -eux; \
+    \
+    apk add --no-cache --virtual .fetch-deps gnupg; \
+    \
+    # https://julialang.org/downloads/#julia-command-line-version
+    # https://julialang-s3.julialang.org/bin/checksums/julia-1.5.3.sha256
+    # this "case" statement is generated via "update.sh"
+    apkArch="$(apk --print-arch)"; \
+    case "$apkArch" in \
+    # amd64
+    x86_64) tarArch='x86_64'; dirArch='x64'; sha256='2faf4ebe3b5fa1bbee853655ef7c292b457e80d3fca1af1c8d3f179286b27da6' ;; \
+    *) echo >&2 "error: current architecture ($apkArch) does not have a corresponding Julia binary release"; exit 1 ;; \
+    esac; \
+    \
+    folder="$(echo "$JULIA_VERSION" | cut -d. -f1-2)"; \
+    wget -O julia.tar.gz.asc "https://julialang-s3.julialang.org/bin/musl/${dirArch}/${folder}/julia-${JULIA_VERSION}-musl-${tarArch}.tar.gz.asc"; \
+    wget -O julia.tar.gz     "https://julialang-s3.julialang.org/bin/musl/${dirArch}/${folder}/julia-${JULIA_VERSION}-musl-${tarArch}.tar.gz"; \
+    \
+    echo "${sha256} *julia.tar.gz" | sha256sum -c -; \
+    \
+    export GNUPGHOME="$(mktemp -d)"; \
+    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$JULIA_GPG"; \
+    gpg --batch --verify julia.tar.gz.asc julia.tar.gz; \
+    command -v gpgconf > /dev/null && gpgconf --kill all; \
+    rm -rf "$GNUPGHOME" julia.tar.gz.asc; \
+    \
+    mkdir "$JULIA_PATH"; \
+    tar -xzf julia.tar.gz -C "$JULIA_PATH" --strip-components 1; \
+    rm julia.tar.gz; \
+    \
+    apk del --no-network .fetch-deps; \
+    \
+    # smoke test
+    julia --version
 
 # add app
 COPY . ./
+
+ENV JULIA_DEPOT_PATH "/server/.julia/packages/:$JULIA_DEPOT_PATH"
+
+RUN julia -e 'import Pkg; Pkg.activate("env"); Pkg.instantiate(); Pkg.precompile()'
+
+# add non root user
+# RUN adduser -D borghi
+# USER borghi
 
 # start app
 CMD ["npm", "run" , "start"]
